### ISSUE TITLE
Images for read me

### ISSUE THREAD

**Issue by jeimyemota** [Jeimyemota/Bamazon#1]
<img width="494" alt="screenshot 71" src="https://user-images.githubusercontent.com/26091374/28653169-0c368334-725a-11e7-8f64-d82051a58935.png">

**Comment by Jeimyemota** [comment]
<img width="882" alt="screenshot 74" src="https://user-images.githubusercontent.com/26091374/28653246-80ea8644-725a-11e7-830e-9d97cc9c6202.png">

**Comment by Jeimyemota** [comment]
<img width="870" alt="screenshot 73" src="https://user-images.githubusercontent.com/26091374/28653265-9f22ceaa-725a-11e7-8341-728bf3757cd1.png">

**Comment by jeimyemota** [comment]
<img width="541" alt="screenshot 72" src="https://user-images.githubusercontent.com/26091374/28653272-aa4df386-725a-11e7-9570-4be29df0f5e2.png">

**Comment by jeimyemota** [comment]
<img width="870" alt="screenshot 73" src="https://user-images.githubusercontent.com/26091374/28653291-c6829be2-725a-11e7-915d-b9d4c6a4b84f.png">

**Comment by jeimyemota** [comment]
<img width="882" alt="screenshot 74" src="https://user-images.githubusercontent.com/26091374/28653301-e3ee89f2-725a-11e7-9bf5-84f4fec2038b.png">

**Comment by jeimyemota** [comment]
<img width="882" alt="screenshot 75" src="https://user-images.githubusercontent.com/26091374/28653343-0a54345c-725b-11e7-84d2-86ab29664d43.png">

**Comment by jeimyemota** [comment]
<img width="882" alt="screenshot 76" src="https://user-images.githubusercontent.com/26091374/28653351-177db464-725b-11e7-98da-61128be9dfa3.png">

**Comment by jeimyemota** [comment]
<img width="882" alt="screenshot 77" src="https://user-images.githubusercontent.com/26091374/28653357-2336e410-725b-11e7-9675-7b2323f8a1e8.png">

**Comment by jeimyemota** [comment]
<img width="685" alt="screenshot 79" src="https://user-images.githubusercontent.com/26091374/28653558-30df7c0c-725c-11e7-9930-78fe2768aea4.png">
